export { AzoaApiClient, DAPP_ROLES } from "./client.js";
export type {
  AzoaApiConfig,
  AvatarResponse,
  TenantKycStatus,
  TenantCustodialAccountStatus,
  TenantCustodialCapabilities,
  TenantKycSession,
  TenantKycDocumentReference,
  TenantKycSubmission,
  // avatar-dapp-rbac: assignable DApp role allowlist
  DappRole,
  NftResult,
  NftMetadata,
  NftMintParams,
  NftTransferParams,
  NftBurnParams,
  NftQueryParams,
  // Allocation types (Fiat Stripe Bridge)
  AllocationRequest,
  AllocationResult,
  // Fungible mint (fungible-mint-and-render-model)
  FungibleMintParams,
  FungibleTokenResult,
  // Swap types
  SwapQuoteParams,
  SwapExecuteParams,
  SwapQuoteResponse,
  BridgeTransactionResult,
  BridgeRouteInfo,
  BridgeInitiateParams,
  SearchResult,
  SearchParams,
  // Wallet types
  WalletResult,
  WalletCreateParams,
  WalletUpdateParams,
  WalletQueryParams,
  PortfolioResult,
  PortfolioAsset,
  PortfolioAssetKind,
  NftHolding,
  // BlockchainOperation types
  BlockchainOperationResult,
  // STARODK types
  STARODKResult,
  STARODKCreateParams,
  STARDappGenerationParams,
  // AvatarNFT types
  AvatarNFTResult,
  AvatarNFTMintParams,
  HolonNFTBindingResult,
  WalletNFTBindingResult,
  // Quest types
  QuestStatus,
  QuestNodeState,
  QuestEdgeType,
  QuestNodeType,
  QuestResult,
  QuestCreateParams,
  QuestUpdateParams,
  QuestNodeResult,
  QuestEdgeResult,
  QuestDependencyResult,
  QuestTemplateResult,
  QuestTemplateCreateParams,
  QuestNodeTemplateResult,
  QuestNodeTemplateCreateParams,
  QuestNodeCreateParams,
  QuestEdgeCreateParams,
  // Quest invitations + request/approval types (quest-invitations-approval)
  QuestRunAccess,
  QuestAccessRequestStatus,
  QuestAccessRequest,
  SetRunAccessRequest,
  InviteAvatarRequest,
  RequestAccessBody,
  DecideAccessRequestBody,
  // ApiKey types
  ApiKeyCreateParams,
  ApiKeyCreateResult,
  ApiKeyInfo,
  SelfIssuableApiKeyScope,
  SelfIssuableApiKeyScopeInfo,
  ApiKeyScope,
  ApiKeyScopeInfo,
  // DappSeries types (DappSeriesController)
  DappSeriesStatus,
  DappSeriesResult,
  DappSeriesCreateParams,
  DappSeriesUpdateParams,
  DappSeriesQuestResult,
  DappSeriesAddQuestParams,
  // Holon AssetType registry types (final-hardening F5)
  HolonTypeResult,
  HolonTypeRegisterParams,
  // Saga operator dead-letter surface (final-hardening Phase-F)
  SagaStepStatus,
  SagaDeadLetterListParams,
  SagaStepView,
  SagaStepRequeueResult,
  SagaStepCancelResult,
  // Wallet wrapping-key rotation (final-hardening B5)
  KeyRotationReport,
  KeyRotationParams,
} from "./client.js";
export { resolveApiPath, API_PATHS } from "./api-version.js";
export type { ApiVersionConfig, ApiController } from "./api-version.js";
